apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/instance: tektonace
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ibm-ace-server-icp4i-prod
    helm.sh/chart: ibm-ace-server-icp4i-prod
    release: tektonace
  name: tektonace-ibm-ace-server-icp4i-prod-config-gen
  namespace: bma-dev
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: tektonace-ibm-ace-server-icp4i-prod-config-gen
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - command:
        - sh
        - -c
        - /server/createwebusers.sh
        image: cp.icr.io/cp/icp4i/ace/ibm-acecc-configurator-prod:11.0.0.8-r1-amd64
        imagePullPolicy: IfNotPresent
        name: config-gen
        resources:
          limits:
            cpu: 500m
            memory: 1028Mi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /server/
          name: tektonace-ibm-ace-server-icp4i-prod-create-configurator-config
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccount: tektonace-ibm-ace-server-icp4i-prod-serviceaccount
      serviceAccountName: tektonace-ibm-ace-server-icp4i-prod-serviceaccount
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 365
          name: tektonace-ibm-ace-server-icp4i-prod-create-configurator-config
        name: tektonace-ibm-ace-server-icp4i-prod-create-configurator-config

