apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: __NAME__
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ibm-ace-server-icp4i-prod
    helm.sh/chart: ibm-ace-server-icp4i-prod
    release: __NAME__
  name: __NAME__-ibm-ace-server-icp4i-prod
spec:
  ports:
  - name: webui
    port: 7600
    protocol: TCP
    targetPort: 7600
  - name: ace-http
    port: 7800
    protocol: TCP
    targetPort: 7800
  - name: ace-https
    port: 7843
    protocol: TCP
    targetPort: 7843
  selector:
    app.kubernetes.io/instance: __NAME__
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ibm-ace-server-icp4i-prod
    helm.sh/chart: ibm-ace-server-icp4i-prod
    release: __NAME__
  type: ClusterIP