apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9483"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: tektonace
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ibm-ace-server-icp4i-prod
    helm.sh/chart: ibm-ace-server-icp4i-prod
    release: tektonace
  name: tektonace-ibm-ace-server-icp4i-prod-ace-metrics
  namespace: bma-dev
spec:
  ports:
  - port: 9483
    protocol: TCP
    targetPort: 9483
  selector:
    app.kubernetes.io/instance: tektonace
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ibm-ace-server-icp4i-prod
    helm.sh/chart: ibm-ace-server-icp4i-prod
    release: tektonace
  sessionAffinity: None
  type: ClusterIP
