apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tektonace
spec:
  serviceAccountName: pipeline
  triggers:
  - name: pullrequest-build-and-deploy
    template:
      name: tektonace-build-and-deploy
    bindings:
    - name: tektonace-build-and-deploy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: tektonace
  name: el-tektonace
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-tektonace