apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tektonace-build-and-deploy
spec:
  params:
  - name: URL
    description: The repository url to build and deploy.
  - name: REVISION
    description: The revision to build and deploy.
  - name: NAMESPACE
    description: The namespace is used by OpenShift's internal image registry to store the built image.
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: build-and-deploy-pipeline-kaniko-nw
      namespace: bma-dev
      labels:
        tekton.dev/pipeline: build-and-deploy-pipeline-kaniko
    spec:
      params:
        - name: pathToContext
          value: .
        - name: pathToYamlFile
          value: acemsdep/
        - name: imageUrl
          value: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/ace11002mqc91ms2
        - name: imageTag
          value: $(params.REVISION)
      pipelineRef:
        name: build-and-deploy-pipeline-kaniko
      resources:
        - name: git-source
          resourceRef:
            name: acems2-git
      serviceAccountName: pipeline
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tektonace-build-and-deploy
spec:
  params:
  - name: REVISION
    value: latest
  - name: NAMESPACE
    value: bma-dev
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tektonace
spec:
  serviceAccountName: pipeline
  triggers:
  - name: pullrequest-build-and-deploy
    template:
      name: tektonace-build-and-deploy
    bindings:
    - name: tektonace-build-and-deploy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: tektonace
  name: el-tektonace
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-tektonace