apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tektonace-build-and-deploy
spec:
  params:
  - name: URL
    description: The repository url to build and deploy.
  - name: REVISION
    description: The revision to build and deploy.
  - name: NAMESPACE
    description: The namespace is used by OpenShift's internal image registry to store the built image.
  - name: NAME
    description: replace name
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: tekton-pipelinerun-build-and-deploy-
      labels:
        tekton.dev/pipeline: build-and-deploy-pipeline-kaniko
    spec:
      params:
        - name: pathToContext
          value: .
        - name: pathToYamlFile
          value: acemsdep/
        - name: imageUrl
          value: image-registry.openshift-image-registry.svc:5000/ace/ace123
        - name: imageTag
          value: $(params.REVISION)
        - name: replaceName
          value: $(params.NAME)
      pipelineRef:
        name: build-and-deploy-pipeline-kaniko
      resources:
        - name: git-source
          resourceRef:
            name: acems2-git
      serviceAccountName: pipeline
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tektonace-build-and-deploy
spec:
  params:
  - name: REVISION
    value: $(body.head_commit.id)
  - name: NAMESPACE
    value: ace
  - name: NAME
    value: acenew
