apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    release: acenew
  name: acenew-ibm-ace-server-icp4i-prod-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acenew-ibm-ace-server-icp4i-prod-role
subjects:
- kind: ServiceAccount
  name: acenew-ibm-ace-server-icp4i-prod-serviceaccount
