apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    release: acedev
  name: acedev-ibm-ace-server-icp4i-prod-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  - deploymentconfigs
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - "apps.openshift.io"
  resources:
  - deploymentconfigs
  verbs:
  - '*' 
