apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-and-deploy-pipeline-kaniko-nw
  labels:
    tekton.dev/pipeline: build-and-deploy-pipeline-kaniko
spec:
  params:
    - name: pathToContext
      value: .
    - name: pathToYamlFile
      value: acemsdep/
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc:5000/ace/ace
    - name: imageTag
      value: latest
  pipelineRef:
    name: build-and-deploy-pipeline-kaniko
  resources:
    - name: git-source
      resourceRef:
        name: acems2-git
  serviceAccountName: pipeline
